spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/db_hospital?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8   #连接池最大默认连接数是 8
        max-wait: -1    #
        max-idle: 8
        min-idle: 0
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: cn.cvs.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl